/* Generated by cbindgen — do not edit manually */

#ifndef STATUSLIGHT_FFI_H
#define STATUSLIGHT_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize logging. Safe to call multiple times.
 */
void statuslight_init(void);

/**
 * Set the light to the given RGB color.
 */
int32_t statuslight_set_rgb(uint8_t r, uint8_t g, uint8_t b);

/**
 * Set the light to a hex color string (e.g., "#FF0000" or "FF0000").
 *
 * # Safety
 *
 * `hex` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t statuslight_set_hex(const char *hex);

/**
 * Set the light to a named preset (e.g., "red", "busy", "in-meeting").
 *
 * # Safety
 *
 * `name` must be a valid, non-null, null-terminated UTF-8 C string.
 */
int32_t statuslight_set_preset(const char *name);

/**
 * Turn the light off.
 */
int32_t statuslight_off(void);

/**
 * Check if any status light device is connected.
 *
 * Returns `1` if connected, `0` if not. Never returns error codes.
 */
int32_t statuslight_is_connected(void);

/**
 * Set the global brightness level (0–100).
 *
 * Returns 0 on success, the clamped brightness value is stored.
 */
int32_t statuslight_set_brightness(uint8_t brightness);

/**
 * Get the current brightness level (0–100).
 */
int32_t statuslight_get_brightness(void);

/**
 * Get the number of connected status light devices.
 */
int32_t statuslight_device_count(void);

#endif  /* STATUSLIGHT_FFI_H */
